### ISSUE TITLE
Error in file upload

### ISSUE THREAD

**Issue by maryamqafari** [lettucebo/MvcDynamicForms#10]
hi i used your code :+1:  as a library and i got below error in file upload :
System.NullReferenceException: 'Object reference not set to an instance of an object.'Mvc Dynamic Form. Cor. Field. FileUploa. PostedFil. get returned null

**Comment by lettucebo** [comment]
Hi 

I try the code earlier, it seems work to me

if you still have a issue, let me know more detail

**Comment by lettucebo** [comment]
cames to my mind

remember to add enctype attribute to form

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))

**Comment by maryamqafari** [comment]
that fixed my problem , thanks.
