### ISSUE TITLE
Show response in Edit mode with the form created

### ISSUE THREAD

**Issue by Kouliga** [lettucebo/MvcDynamicForms#5]
Hi, 

i hope you guys are going very fine. 
Please, i am using this dll in my project to create a dynamic metadata web application to manage verbal autopsy data. But after the creation of the form and the data entry. i am struggling to display responses in the from created for edit mode. Then if the user made mistakes, they can go in the edit mode to do some corrections. 
If someone knows how to do that with this dll, i will be very grateful!!

Regards,

**Comment by lettucebo** [comment]
Hi

Recently I encounter job relate problem, I can not deal this issue faster, Sorry about this

Want to use this library with edit mode is simple

In the Each Abstract Field based class have different name property but does same purpose: Get or Set the value

- TextField called: Value
  - <https://github.com/lettucebo/MvcDynamicForms/blob/master/MvcDynamicForms.Core/Fields/Abstract/TextField.cs#L30>
- ListField called: Choices
  - <https://github.com/lettucebo/MvcDynamicForms/blob/master/MvcDynamicForms.Core/Fields/Abstract/ListField.cs#L42>

For example
![image](https://cloud.githubusercontent.com/assets/891383/24119130/2275bec2-0deb-11e7-8e74-45bd023356ba.png)
![image](https://cloud.githubusercontent.com/assets/891383/24119258/8546b27c-0deb-11e7-86d8-36f9a6468fe3.png)


Can get the result:
![image](https://cloud.githubusercontent.com/assets/891383/24119232/6ddee456-0deb-11e7-88e4-703f1d24b92c.png)
