### ISSUE TITLE
Assemblies are not signed

### ISSUE THREAD

**Issue by CamiloBernal** [lettucebo/MvcDynamicForms#6]
Hello,

I am trying to use your package with a solution that requires all of our assemblies to be signed. I am unable to build my solution with this package referenced because the assembly it adds is not signed. Is it possible for that to be added?

Thanks,

Camilo

**Comment by lettucebo** [comment]
Hi

Let me see what I can do

紙鈔魚
[image: Facebook] <https://www.facebook.com/lettucebo> [image: Twitter]
<https://twitter.com/abc12207> [image: about.me] <http://about.me/money.yu>

2016-11-10 6:02 GMT+08:00 Camilo Bernal <notifications@github.com>:

**Comment by lettucebo** [comment]
@CamiloBernal 

I have sign the assembly and publish a new library(1.1.0) to nuget

let me know if still have problem

thank you

**Comment by CamiloBernal** [comment]
Great, @lettucebo . Thank you very much, we are already testing the new version.
